use_frameworks!

target 'TWImageBrowser_Example' do
  pod 'TWImageBrowser', :path => '../'
end

target 'TWImageBrowser_Tests' do
    pod 'TWImageBrowser', :path => '../'
    pod 'FBSnapshotTestCase'
end